-- DB 작업 전 account 생성
-- SQL Command Line 으로 직접 타이핑 요망
-- CREATE TABLESPACE sugo2day DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\sugo2day.dbf' SIZE 500M;
-- CREATE USER sugo2day IDENTIFIED BY 1234 DEFAULT TABLESPACE sugo2day TEMPORARY TABLESPACE temp;
-- GRANT connect, resource, dba TO sugo2day;

-- 아래 쿼리 전체를 복사해서 sqldeveloper에서 쿼리 실행

--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SUGO2DAY"."MEMBER" 
   (	"ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"BIRTHDAY" DATE, 
	"GENDER" VARCHAR2(100 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  DDL for Index MEMBER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUGO2DAY"."MEMBER_ID_PK" ON "SUGO2DAY"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  DDL for Index MEMBER_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUGO2DAY"."MEMBER_EMAIL_UK" ON "SUGO2DAY"."MEMBER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  DDL for Index MEMBER_NAME_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUGO2DAY"."MEMBER_NAME_UK" ON "SUGO2DAY"."MEMBER" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SUGO2DAY"."MEMBER" ADD CONSTRAINT "MEMBER_NAME_UK" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY"  ENABLE;
  ALTER TABLE "SUGO2DAY"."MEMBER" ADD CONSTRAINT "MEMBER_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY"  ENABLE;
  ALTER TABLE "SUGO2DAY"."MEMBER" ADD CONSTRAINT "MEMBER_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY"  ENABLE;
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);

  
  
  --------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LETTER
--------------------------------------------------------

  CREATE TABLE "SUGO2DAY"."LETTER" 
   (	"L_NUM" NUMBER, 
	"L_WRITER" VARCHAR2(20 BYTE), 
	"L_CONTENT" VARCHAR2(4000 BYTE), 
	"L_FILES" VARCHAR2(100 BYTE) DEFAULT '/', 
	"L_REGDATE" DATE, 
	"L_ISQUEST" VARCHAR2(20 BYTE), 
	"L_ISPRIVATE" VARCHAR2(20 BYTE), 
	"L_QUESTCATE" VARCHAR2(50 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ; 
--------------------------------------------------------
--  DDL for Index LETTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUGO2DAY"."LETTER_PK" ON "SUGO2DAY"."LETTER" ("L_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  Constraints for Table LETTER
--------------------------------------------------------

  ALTER TABLE "SUGO2DAY"."LETTER" MODIFY ("L_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."LETTER" ADD CONSTRAINT "LETTER_PK" PRIMARY KEY ("L_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY"  ENABLE;
  ALTER TABLE "SUGO2DAY"."LETTER" MODIFY ("L_ISPRIVATE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."LETTER" MODIFY ("L_ISQUEST" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."LETTER" MODIFY ("L_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."LETTER" MODIFY ("L_WRITER" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."LETTER" MODIFY ("L_NUM" NOT NULL ENABLE);

  
  
  
  --------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUEST
--------------------------------------------------------

  CREATE TABLE "SUGO2DAY"."QUEST" 
   (	"Q_NUM" NUMBER, 
	"Q_TITLE" VARCHAR2(50 BYTE), 
	"Q_DESCRIPT" VARCHAR2(4000 BYTE), 
	"Q_STARTDATE" DATE, 
	"Q_ENDDATE" DATE, 
	"Q_ISPRIVATE" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"Q_WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  DDL for Index QUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUGO2DAY"."QUEST_PK" ON "SUGO2DAY"."QUEST" ("Q_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  DDL for Index QUEST_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SUGO2DAY"."QUEST_UK1" ON "SUGO2DAY"."QUEST" ("Q_TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY" ;
--------------------------------------------------------
--  Constraints for Table QUEST
--------------------------------------------------------

  ALTER TABLE "SUGO2DAY"."QUEST" ADD CONSTRAINT "QUEST_UK1" UNIQUE ("Q_TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY"  ENABLE;
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_WRITER" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."QUEST" ADD CONSTRAINT "QUEST_PK" PRIMARY KEY ("Q_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUGO2DAY"  ENABLE;
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_ISPRIVATE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_DESCRIPT" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SUGO2DAY"."QUEST" MODIFY ("Q_NUM" NOT NULL ENABLE);
  
  -- sequence
  CREATE SEQUENCE mID_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
  CREATE SEQUENCE lnum_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
  CREATE SEQUENCE qnum_seq START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;
  
